[build]
  command = "astro build"
  publish = "dist"
  functions = "netlify/functions"


[dev]
  framework = "astro"
  targetPort = 4321
  port = 8888

[functions]
  node_bundler = "esbuild"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true